### ISSUE TITLE
Improve CFlags()

### ISSUE THREAD

**Issue by hkumar6** [eddelbuettel/rcppgsl#14]
The `RcppGSL::CFlags()` currently gives the location of the GSL headers on the machine but not the `RcppGSL.h` file. It would be nice to have the function return locations of both files. A similar function is present in the [RcppArmadillo](https://github.com/RcppCore/RcppArmadillo/blob/master/R/flags.R) package too.
@eddelbuettel If you think this makes sense, I could create a pull request.

**Comment by eddelbuettel** [comment]
But RcppGSL.h comes in as soon as you do `Build-Depends: RcppGSL`.

I think the basic idea was CFlags for GSL itself, and to rely on R as usual for find the per-package header.

The RcppArmadillo function may be a left-over.

**Comment by hkumar6** [comment]
@eddelbuettel  Thank you for the explanation.
I was struggling with the Makevars earlier and somehow missed the `Build-Depends` field.
