### ISSUE TITLE
Add appveyor.yml and badge

### ISSUE THREAD

**Issue by jtrecenti** [eddelbuettel/rcppgsl#15]
Is it possible to add an appveyor.yml file to test CI in Windows?

**Comment by eddelbuettel** [comment]
In principle it is indeed, in practice I do not bother for 100+ repos.  This one is extra hard because you need the GSL on Windows, so I am rather unlikely to bother.

You are of course free to fork, set it all up and demonstrate to me how easy it all is.

**Comment by jtrecenti** [comment]
Thank you!

We are trying to do this based on @stewid solution to https://github.com/stewid/SimInf but our shell knowledge is very limited. We are trying to build this https://github.com/brsantos/baquantreg.

Maybe @stewid could help on this?

**Comment by eddelbuettel** [comment]
For packaging question, including testing, I recommend the r-package-devel mailing list.  

Please don't use this package's issue tickets as a substitute.
