### ISSUE TITLE
Shallow-copy `Vector` then `free()` both causes segfault

### ISSUE THREAD

**Issue by stephematician** [eddelbuettel/rcppgsl#21]
An example of the shallow-copy of `Vector` and `free()` causing R to segfault; I suppose this can either be solved via a deep-copy, some kind of shared-pointer like management of the resource, or updating documentation to reflect the limitation?

```r
    fx <- Rcpp::cppFunction("
    void vec_rcppgsl_uhoh(RcppGSL::Vector vec) {
        RcppGSL::Vector uh_oh = vec;
        vec.free();
        uh_oh.free();

    }", depends="RcppGSL")

    a <- 10
    vec_rcppgsl_uhoh(a)
    gc()
```

**Comment by eddelbuettel** [comment]
No, that is simply user error.  We 
- say this is C memory management, 
- say you do not need it anymore (!!!) 
- made a change to free in the destructor for you

so if you do it manually do it twice you get to keep the piece.  I don't see anything actionable here and plan to close this.

**Comment by eddelbuettel** [comment]
I think that is simply a double `free()` will will always seg.fault.  

We could try to be clever and assign an explicit `nullptr` after freeing.  In a way we already tried to approximate that with logical var.   But GSL really is a C library so there are limits -- and what we have is a) a shallow copy on purpose (as costlier deep copies are generally avoided) and then b) a double call to `free`.  Bang.  

I don't see how we can do better here.   Do you?

**Comment by stephematician** [comment]
I wish I had the answers!

I wouldn't want to over-complicate things to the degree of implementing a smart-pointer-like approach. It might be best to document that the copies are shallow and then let user beware.

**Comment by eddelbuettel** [comment]
Yep. It "looks so simple" but isn't.  I have been around GSL as its Debian maintainer for over 20 years.  And already then several proposals / forks existed that tried to take the GSL to C++.  None ever made it.  Doing it really really well is just so damn hard.
