### ISSUE TITLE
Rprintf does not print correct value of vector with RcppGSL sugar

### ISSUE THREAD

**Issue by nettoyoussef** [eddelbuettel/rcppgsl#27]
Hi Dirk, thanks for the awesome work. 
I am using it to port some gsl routines to R! :)

I think I found some unexpected behavior in the package, but feel free to correct me if I am wrong.
The function Rprintf is not able to print the value of an array using RcppGSL sugar.
Consider the function below:

```c++
// [[Rcpp::export]]
void print_gsl(unsigned n){

  RcppGSL::vector<double> y(n);

  for(unsigned i =0; i<n; ++i){
    gsl_vector_set(y, i, i+1);
  }

  Rprintf("\nUsing Rprintf:\n");

  Rprintf("Printing y[1] without get: %.2f\n",y[1]);
  Rprintf("Printing y[1] with get: %.2f\n", gsl_vector_get(y,1));

  Rprintf("\nUsing Rcout:\n");
  Rcpp::Rcout <<
    "Printing y[1] without get: " << y[1] << std::endl;

  Rcpp::Rcout <<
    "Printing y[1] with get: " << gsl_vector_get(y,1) << std::endl;
  
}

```
On R:

```R
print_gsl(5)

# > Using Rprintf:
# > Printing y[1] without get: 0.00
# > Printing y[1] with get: 2.00

# > Using Rcout:
# > Printing y[1] without get: 2
# > Printing y[1] with get: 2

```
This is not mentioned in the documentation (at least that I am aware of), and it was making it hard to find the source of some bugs in my program.

**Comment by eddelbuettel** [comment]
Eeek.  That is indeed annoying.   But given that GSL is written in C there is a limit to what we can do with C++ magic so documenting, as you suggest, may be the best bet.

**Comment by eddelbuettel** [comment]
Adding a new subsection:

![image](https://user-images.githubusercontent.com/673121/100550975-73af5480-3243-11eb-8de4-9e76c96cb0b6.png)
