### ISSUE TITLE
Consider removing the addition of FLIBS

### ISSUE THREAD

**Issue by hsloot** [eddelbuettel/rcppgsl#31]
If there is a non-obvious reason why `FLIBS` must be added with the RcppGSL attribute; please close.

## Summary

Using RcppGSL attributes adds `FLIBS` (see below). This causes issues for users of Arm64 binaries on MacOS, which do not have the Fortran compiler included (see https://cran.r-project.org/bin/macosx/). In this case, compilation fails. I tested a version that does not include `FLIBS`; it can be installed and all tests are successful. Hence, I wonder if adding `FLIBS` could be removed or made optional.

https://github.com/eddelbuettel/rcppgsl/blob/cf6fb4781d62433c47303096e1f4f672bb059228/R/inline.R#L49-L51

## Note 

Users can fix this by installing the Fortran compiler as instructed. However, in some cases, the Fortran compiler seems to be needed only to avoid a "path does not exist"-error and not any compilation itself.

**Comment by eddelbuettel** [comment]
That is (was ?) the current recommensation of _Writing R Extension_, the only official source of package building documentation, for well over a decade.

If you have contrary and _official_ recommendations, please share them. In absence of that I close this.  As I could be behind the news feel free to reopen _if and when you have official sources not to include `$(FLIBS)`_ .  As of course, as always, _empty_ variables get filled in as empty and hence do exactly zero harm.

**Comment by hsloot** [comment]
I was not aware of this. Thanks for the quick response. After a quick search, I suppose, you are referring to this part from WRE 1.2.1:

> If BLAS_LIBS is included, then FLIBS also needs to be included following it, as most BLAS libraries are written at least partially in Fortran.

Not including FLIBS worked on my system, but it may be different on others or with other usecases.

Your note about an empty FLIBS variable is correct. Interestingly, the current binary (for Arm64 MacOS) seems to set FLIBS in the Makeconf file to some non-existent path — likely a result of building R with a Fortran compiler and not including it in the binaries.

**Comment by eddelbuettel** [comment]
It could well be that something "is more complicated" on arm64 depending on where you got compilers from, the whole nightmare about Apple not providing a Fortran compiler (!!) and whatnot.  On "normal systems" things just work so we should strive to get arm64 to behave too.  Help welcome (and no, I don't have such a machine myself).

**Comment by hsloot** [comment]
I have one final question about this topic. Apologies if I am totally misunderstanding the whole thing.

I now understand that following WRE, adding `BLAS_LIBS` requires adding `FLIBS` and adding `LAPACK_LIBS` requires adding `BLAS_LIBS` and `FLIBS`. I also assume the intention of adding those is to link to the same BLAS implementation as R does instead of GSL's own BLAS for GSL-related code. However, (as I understand)

* The package itself and the example package do not seem to link to R's BLAS (anymore?) and fall back on GSL's BLAS,
* while the inline pluggin adds `$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)` to use the version of BLAS used by R.

The different approaches confuse me. Maybe I am missing something, but does this not imply the same code may work differently when it's compiled indirectly via `Rcpp::sourceCpp` instead of in an R package following the provided example? 

I have also successfully tested on my machine and with your CI workflow on GH actions the following changed version of `inlineCxxPlugin`:

```r
inlineCxxPlugin <- function(...) {
    plugin <- Rcpp::Rcpp.plugin.maker(
        include.before = "#include <RcppGSL.h>",
        libs = sprintf( "%s", LdFlags(FALSE)), 
        # + libs = sprintf( "%s", LdFlags(FALSE)), 
        # - libs = sprintf( "%s $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)", LdFlags(FALSE)),
        package = "RcppGSL", Makevars = NULL, Makevars.win = NULL
    )
    settings <- plugin()
    settings$env$PKG_CPPFLAGS <- CFlags(FALSE)
    settings$configure <- readLines(system.file("skeleton", "configure", package="RcppGSL"))
    settings$configure.win <- readLines(system.file("skeleton", "configure.win", package="RcppGSL"))
    settings$Makevars.in <- readLines(system.file("skeleton", "Makevars.in", package = "RcppGSL"))
    settings
}
```

In the end, I am wondering if it would not be better for the inline plugin to fall back on GSL's BLAS library, too, or provide an option to do that. This would
* make sure the same BLAS is used independent of whether using a packaged or `Rcpp::sourceCpp` approach,
* and allow Arm64 MacOS users to use the `Rcpp::depends(RcppGSL)`-attribute without installing the Fortran compiler (I use R quite a bit, never needed it before, and the binaries require 3 times the space of R's) or having to research how to modify the setup such that it works without installing it.

**Comment by eddelbuettel** [comment]
There are two aspects here.

One is `FLIBS` etc.  For example in `RcppArmadillo` we have for likely well over a decade always unconditionally provided the variable settings _and that is The Right Thing (TM)_ as evidenced by a few StackOverflow etc questions of the years.  We need this, we ship this (here pointing at the file included by the package creation helper: https://github.com/RcppCore/RcppArmadillo/blob/master/inst/skeleton/Makevars).  You can search at GitHub, most of the by now 1100 RcppArmadillo packages will do this.

Second is GSL and its small copy blas in its own library. I have maintained the GNU GSL in Debian for likely 25 years now so I know this one, I still don't understand it.  In any event it does not _force you to link one way or the other_ as BLAS and LAPACK are _interfaces_ and you can swap them in and out.  Ie use MKL, or OpenBLAS, or ...  So I do not think the RcppGSL package does anything wrong or unusual apart from accomodation upstream GSL and its little `libgslcblas` needed by `libgsl`.

Of course, I could (even after all these years) be overlooking something so if you found a bug let me know.
