### ISSUE TITLE
Set error hander on package init?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppgsl#5]
Thinking some more about #4, I can't think of a reason _not_ to do this on package initialization.

Any thoughts, @thirdwing ?

**Comment by thirdwing** [comment]
It should be done on package initialization. As in the GSL manual [1]:

> This function turns off the error handler by defining an error handler which does nothing.
> This will cause the program to continue after any error, so the return values from any library routines must be checked. 
> This is the recommended behavior for production programs. 

[1] http://www.gnu.org/software/gsl/manual/html_node/Error-Handlers.html#Error-Handlers

**Comment by eddelbuettel** [comment]
I fully agree, and I'll take care of it.

**Comment by eddelbuettel** [comment]
Oh, and I just did but forgot the entry in the commit log message.  

See 7195b664cf14dd4e2e1bf8f043a1396c45cb8a9b and 179bae447a9c22bfa6605ac27e83b8213e235286.  

Will update documentation as well with a line.
